name: Backporting
author: Thibault Derousseaux <tibdex@gmail.com>
description: Automatically backport PRs to other branches by simply labeling them.
inputs:
  add_labels:
    description: Comma separated list of labels to add to the backport PR.
    required: false
  files_to_skip:
    description: Comma seperated list of files to be skipped from the backport
    required: false
  branch_name:
    description: Custom branch name for the backport PR.
    required: false
  delete_branch:
    description: Delete the backport branch created after the backport PR is merged.
    required: false
    default: true
  github_token:
    description: Token for the GitHub API.
    required: true
  title_template:
    description: Template for the title of the backport PR.
    required: false
    default: "[Backport {{base}}] {{originalTitle}}"
runs:
  using: node12
  main: dist/index.js
branding:
  icon: arrow-left-circle
  color: purple
